### ISSUE TITLE
ImportError: No module named loader

### ISSUE THREAD

**Issue by AmitMY** [renj/pseudo-ref#1]
Thanks for this code.

First, the README is missing two dependencies: `matplotlib` and `scipy`.

When running the command from the README, I get an error:

> Traceback (most recent call last):
>   File "lattice.py", line 2, in <module>
>     import msa_class
>   File "/home/nlp/amit/pseudo-ref/msa_class.py", line 15, in <module>
>     import loader
> ImportError: No module named loader

I am assuming that that is because of 
```py
sys.path.append('../pytorch-examples/word_language_model/')
```

But I haven't found any indication in https://github.com/pytorch/examples/tree/master/word_language_model of a `loader`.

Can you please add instructions on how to get `loader`? or maybe add it to this repo as well?

**Comment by renj** [comment]
Thank you Amit for pointing out this bug. `loader` actually is in `language_model`. I've just fixed this.

**Comment by AmitMY** [comment]
Great, thanks!
One more dependency missing is `nltk`.

Also, it now fails to import `Model`:

> ========= READ DATA COMPLETE ===========
> Traceback (most recent call last):
>   File "lattice.py", line 607, in <module>
>     lm_model = torch.load(f, map_location=lambda storage, loc: storage)
>   File "/home/nlp/amit/anaconda2/envs/pseudo-ref/lib/python2.7/site-packages/torch/serialization.py", line 358, in load
>     return _load(f, map_location, pickle_module)
>   File "/home/nlp/amit/anaconda2/envs/pseudo-ref/lib/python2.7/site-packages/torch/serialization.py", line 542, in _load
>     result = unpickler.load()
> ImportError: No module named Model

**Comment by renj** [comment]
It's fixed now. `language_model` should be added into path.

**Comment by AmitMY** [comment]
Thanks. This works! I am running the soft code overnight, as it seems to take seconds for some sentences, but many minutes for others, but I ran it on a sample and it worked.

**Comment by renj** [comment]
> Thanks. This works! I am running the soft code overnight, as it seems to take seconds for some sentences, but many minutes for others, but I ran it on a sample and it worked.

Yes. If the lattice is complex, it will take a long time to generate the pseudo-sentences. Actually you can do some optimization on it, e.g. cache the suffixes of each nodes instead of simple DFS.
